[2023-03-23 23:06:37,522] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.criar_pasta manual__2023-03-24T02:06:33.515424+00:00 [queued]>
[2023-03-23 23:06:37,525] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.criar_pasta manual__2023-03-24T02:06:33.515424+00:00 [queued]>
[2023-03-23 23:06:37,525] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 23:06:37,525] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-23 23:06:37,525] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-23 23:06:37,531] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): criar_pasta> on 2023-03-24 02:06:33.515424+00:00
[2023-03-23 23:06:37,534] {standard_task_runner.py:52} INFO - Started process 2289 to run task
[2023-03-23 23:06:37,537] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'criar_pasta', 'manual__2023-03-24T02:06:33.515424+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/var/folders/1t/ncp0s87s3bd37gfvks3bsb3w0000gn/T/tmpm_j_rd3f', '--error-file', '/var/folders/1t/ncp0s87s3bd37gfvks3bsb3w0000gn/T/tmpx_kub04l']
[2023-03-23 23:06:37,538] {standard_task_runner.py:80} INFO - Job 17: Subtask criar_pasta
[2023-03-23 23:06:37,565] {task_command.py:370} INFO - Running <TaskInstance: first_dag.criar_pasta manual__2023-03-24T02:06:33.515424+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2023-03-23 23:06:37,591] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=criar_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-03-24T02:06:33.515424+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-24T02:06:33.515424+00:00
[2023-03-23 23:06:37,591] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/1t/ncp0s87s3bd37gfvks3bsb3w0000gn/T
[2023-03-23 23:06:37,592] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir "~/Documents/projects/weather-data/pasta"']
[2023-03-23 23:06:37,600] {subprocess.py:85} INFO - Output:
[2023-03-23 23:06:37,613] {subprocess.py:92} INFO - mkdir: ~/Documents/projects/weather-data: No such file or directory
[2023-03-23 23:06:37,613] {subprocess.py:96} INFO - Command exited with return code 1
[2023-03-23 23:06:37,620] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-23 23:06:37,621] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=first_dag, task_id=criar_pasta, execution_date=20230324T020633, start_date=20230324T020637, end_date=20230324T020637
[2023-03-23 23:06:37,625] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task criar_pasta (Bash command failed. The command returned a non-zero exit code 1.; 2289)
[2023-03-23 23:06:37,639] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-23 23:06:37,649] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
